# Generated by Django 5.0.14 on 2026-07-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_add_resume_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdevice',
            name='ticket_number_current',
            field=models.BigIntegerField(default=5000000001),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='ticket_number_end',
            field=models.BigIntegerField(default=5000999999),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='ticket_number_start',
            field=models.BigIntegerField(default=5000000001),
        ),
    ]
