# Generated by Django 5.0.14 on 2026-07-07 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_agentdevice_ticket_number_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='accounts.agent')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent', '-timestamp'], name='idx_agent_loc_time'), models.Index(fields=['timestamp'], name='idx_loc_time')],
            },
        ),
    ]
