# Generated by Django 5.0.14 on 2026-09-17 18:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_agentlocationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='borlette',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='Admin VIP : compte jamais bloqué, abonnement prolongé automatiquement'),
        ),
        migrations.AddField(
            model_name='borlette',
            name='vip_lifetime_free',
            field=models.BooleanField(default=False, help_text='VIP Abonnement à vie : exempté de paiement sans bouton de paiement'),
        ),
        migrations.AddField(
            model_name='globalpaymentsettings',
            name='accumulated_profit_reset_date',
            field=models.DateTimeField(blank=True, help_text='Date de réinitialisation du montant des profits accumulés par le Superadmin', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('AFFILIATE', 'Affiliate'), ('PARTNER', 'Partenaire'), ('SOUS_DIRECTEUR', 'Sous-Directeur')], default='ADMIN', max_length=32),
        ),
        migrations.CreateModel(
            name='SousDirecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('14.00'), help_text='Pourcentage attribué par le directeur (ex: 14.00%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borlette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_directeurs', to='accounts.borlette')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sous_directeur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sous-Directeur',
                'verbose_name_plural': 'Sous-Directeurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='sous_directeur',
            field=models.ForeignKey(blank=True, help_text='Sous-directeur responsable de cet agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='accounts.sousdirecteur'),
        ),
        migrations.CreateModel(
            name='SousDirecteurTiragePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sous_directeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirage_preferences', to='accounts.sousdirecteur')),
                ('tirage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_directeur_preferences', to='accounts.tirage')),
            ],
            options={
                'indexes': [models.Index(fields=['sous_directeur', 'tirage'], name='idx_sd_tirage'), models.Index(fields=['sous_directeur', 'actif'], name='idx_sd_actif')],
            },
        ),
        migrations.AddConstraint(
            model_name='sousdirecteurtiragepreference',
            constraint=models.UniqueConstraint(fields=('sous_directeur', 'tirage'), name='uniq_sous_dir_tirage_pref'),
        ),
    ]
