# Generated by Django 5.1.4 on 2026-07-01 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_portal', '0010_add_option_to_ticketline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketIdentity',
            fields=[
                ('global_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('server_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('sync_status', models.CharField(choices=[('DRAFT', 'Draft'), ('LOCAL_SIGNED', 'Local Signed'), ('LOCAL_PRINTED', 'Local Printed'), ('SYNC_PENDING', 'Sync Pending'), ('QUEUED_GATEWAY', 'Queued Gateway'), ('PROCESSING', 'Processing'), ('SYNCED_VALID', 'Synced Valid'), ('CONFLICT', 'Conflict'), ('SETTLED_LOST', 'Settled / Lost'), ('SETTLED_WON', 'Settled / Won'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('integrity_hash', models.CharField(blank=True, default='', max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('origin_station', models.CharField(db_index=True, max_length=128)),
                ('sequence_number', models.BigIntegerField(default=0)),
                ('signature_version', models.IntegerField(default=1)),
                ('game_session', models.CharField(db_index=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Ticket Identity',
                'verbose_name_plural': 'Ticket Identities',
                'indexes': [models.Index(fields=['device_id', 'sequence_number'], name='idx_tident_dev_seq'), models.Index(fields=['sync_status'], name='idx_tident_status')],
            },
        ),
    ]
