# Generated by Django 5.1.4 on 2026-07-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_portal', '0011_ticketidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketidentity',
            name='ticket_origin',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('RECOVERY', 'Recovery'), ('MANUAL_IMPORT', 'Manual Import')], default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketidentity',
            name='validation_level',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('SERVER', 'Server'), ('CRYPTO', 'Crypto'), ('FINAL', 'Final')], default='SERVER', max_length=20),
        ),
    ]
