# Generated by Django 5.1.4 on 2026-07-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_portal', '0012_ticketidentity_ticket_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketidentity',
            name='sync_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('LOCAL_SIGNED', 'Local Signed'), ('LOCAL_PRINTED', 'Local Printed'), ('SYNC_PENDING', 'Sync Pending'), ('QUEUED_GATEWAY', 'Queued Gateway'), ('PROCESSING', 'Processing'), ('SYNCED_VALID', 'Synced Valid'), ('CONFLICT', 'Conflict'), ('SETTLED_LOST', 'Settled / Lost'), ('SETTLED_WON', 'Settled / Won'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived'), ('VALIDATION_PENDING', 'Validation Pending')], default='DRAFT', max_length=20),
        ),
    ]
